# Site settings
title: Biblioteca Druídica
email: "greum [at] gmail.com"
description: >
  Acervo de RPG.
baseurl: ""
url: "https://bibliotecadruidica.github.io"
language: "pt-BR"
timezone: "America/Sao_Paulo"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Coleções
#Coleções:
#  Livros:
#    output: false

sass:
  style: compressed

# Arquivos que não precisam ser publicados (limpeza)
exclude:
  - jquery-1.3.2.js
